[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173

[[context.production.environment]]
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""

[[context.preview.environment]]
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""

[[context.branch-deploy.environment]]
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""
